name: Data Warehouse ETL Pipeline

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Pobranie kodu
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalacja MS ODBC 18
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
        curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

    - name: Instalacja bibliotek
      run: pip install pandas requests sqlalchemy pyodbc

    - name: Uruchomienie ETL
      env:
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
      run: python etl.py